permalink: /:categories/:year/:month/:day/:title 

title: Aaronsz's Blog
description: A blog you've never seen before!
author:
  name: Aaronsz Xia
  email: 1197393094@qq.com
  github: aaronszxia
  weibo:
    username: "华之腾啊"
    link: https://weibo.com/u/2185032634/
  qq: 1197393094
  twitter: aaronszxia
  feedburner: feedname

JB :
  archive_path: /archive.html
  categories_path: /categories.html
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /rss.xml

  comments:
    provider: gitalk
    duoshuo:
      short_name : jekyllbootstrap
    gitalk:
      clientID: a86c2379ac1cc4fbc303
      clientSecret: 0e301c07a8734a5a78865d5e2b8c0b312e0d8073
      repo: aaronszxia.github.io
      owner: aaronszxia
      admin: ["admin_1", "admin_2", "admin_3"]    # 由于技术原因，请到 /_includes/JB/comments-providers/gitalk 文件中修改
      id: md5(location.pathname)                  # Ensure uniqueness and length less than 50
      distractionFreeMode: false                  # Facebook-like distraction free mode
   
  analytics:
    provider: baidu
    google: 
        tracking_id: 'UA-138729552-1'
      
# 如果你的个人网站项目不是放在 username.github.io 仓库，而是放在了名为 repo 的仓库里，需要添加一个如下的 baseurl
# baseurl: "/repo"